HISTORY = 5

NUM_SENSORS = 16
OBSERVATION_SIZE = NUM_SENSORS + 4 + 4 #numero de sensores, + velocidade individual de rodas + ação

FORWARD_SPEED = 3.0
TURN_SPEED = 4.0

SENSOR_LIMIT = 1024.0
COLLISION_THRESHOLD = 0.8
SIDE_COLLISION_THRESHOLD = 0.98
MAX_STEPS = 5000

FRONT_SENSOR_IDS = (2, 3, 4, 5)
LEFT_SENSOR_IDS = (0, 1, 2)
RIGHT_SENSOR_IDS = (5, 6, 7)

RANDOM_SPAWN = True

# Mantem margem para o corpo do robo e evita comecar apontado para parede.
SPAWN_X_RANGE = (-1.25, 1.25)
SPAWN_Y_RANGE = (-1.25, 1.25)

# Valores em radianos -pi a pi;
SPAWN_YAW_RANGE = (-3.14159, 3.14159)
SPAWN_MAX_START_DANGER = 0.45
SPAWN_MAX_ATTEMPTS = 20

SPAWN_BLOCKED_OBJECT_TYPES = ("OilBarrel",)
SPAWN_MIN_OBJECT_DISTANCE = 0.85
