HISTORY = 5

NUM_SENSORS = 16
OBSERVATION_SIZE = NUM_SENSORS + 4 + 4 #numero de sensores, + velocidade individual de rodas + ação

FORWARD_SPEED = 3.0
TURN_SPEED = 4.0

SENSOR_LIMIT = 1024.0
COLLISION_THRESHOLD = 0.8
MAX_STEPS = 1000

FRONT_SENSOR_IDS = (2, 3, 4, 5)
LEFT_SENSOR_IDS = (0, 1, 2)
RIGHT_SENSOR_IDS = (5, 6, 7)
